//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FSBT_HHT_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BackupHistory
    {
        public BackupHistory()
        {
            this.BackupHistoryDetails = new HashSet<BackupHistoryDetail>();
        }
    
        public int BackupID { get; set; }
        public string BackupName { get; set; }
        public bool Deleted { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public string DeleteBy { get; set; }
    
        public virtual ICollection<BackupHistoryDetail> BackupHistoryDetails { get; set; }
    }
}
