//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FSBT_HHT_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfigFileFormatDetail
    {
        public int FileDetailID { get; set; }
        public Nullable<int> FileID { get; set; }
        public Nullable<int> ColumnNo { get; set; }
        public string PrimaryKey { get; set; }
        public string Field { get; set; }
        public string Description { get; set; }
        public string Type { get; set; }
        public Nullable<int> Length { get; set; }
        public string Required { get; set; }
        public string Default { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdateBy { get; set; }
        public string AllFilePrimaryKey { get; set; }
    }
}
