//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FSBT_HHT_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfigUserGroupPermission
    {
        public string GroupID { get; set; }
        public string ScreenID { get; set; }
        public string ComponentName { get; set; }
        public string ComponentType { get; set; }
        public string ComponentAlias { get; set; }
        public bool AllowAdd { get; set; }
        public bool AllowEdit { get; set; }
        public bool AllowDelete { get; set; }
        public bool Enable { get; set; }
        public bool Visible { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public string UpdateBy { get; set; }
    
        public virtual ConfigUserGroupScreen ConfigUserGroupScreen { get; set; }
    }
}
