//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FSBT_HHT_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfigFileDetailAS400
    {
        public int FileDetailID { get; set; }
        public int FileID { get; set; }
        public int Index { get; set; }
        public string PrimaryKey { get; set; }
        public string Field { get; set; }
        public string Description { get; set; }
        public string Type { get; set; }
        public int Length { get; set; }
        public int DecPos { get; set; }
        public int StartPos { get; set; }
        public int EndPos { get; set; }
        public string Default { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public string UpdateBy { get; set; }
    
        public virtual ConfigFileAS400 ConfigFileAS400 { get; set; }
    }
}
