//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FSBT_HHT_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HHTStocktaking
    {
        public string StocktakingID { get; set; }
        public int ScanMode { get; set; }
        public string LocationCode { get; set; }
        public string Barcode { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> NewQuantity { get; set; }
        public int UnitCode { get; set; }
        public string Flag { get; set; }
        public string Description { get; set; }
        public string SKUCode { get; set; }
        public string ExBarCode { get; set; }
        public string InBarCode { get; set; }
        public bool SKUMode { get; set; }
        public string HHTName { get; set; }
        public System.DateTime CountDate { get; set; }
        public string DepartmentCode { get; set; }
        public string MKCode { get; set; }
        public string ProductType { get; set; }
        public bool FlagPrint { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public string UpdateBy { get; set; }
        public string SerialNumber { get; set; }
        public string ConversionCounter { get; set; }
        public string StorageLocation { get; set; }
        public string StorageLocationDesc { get; set; }
        public string Plant { get; set; }
        public string PIDoc { get; set; }
        public string MCHLevel1 { get; set; }
        public string MCHLevel2 { get; set; }
        public string MCHLevel3 { get; set; }
        public string MaterialGroup { get; set; }
        public string ComputerName { get; set; }
    }
}
