//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FSBT_HHT_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogError
    {
        public int LogId { get; set; }
        public string Username { get; set; }
        public string ErrorClass { get; set; }
        public string ErrorMethod { get; set; }
        public string Exception { get; set; }
        public System.DateTime ErrorDate { get; set; }
    }
}
