//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FSBT_HHT_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterSKU
    {
        public string ExBarcode { get; set; }
        public string InBarcode { get; set; }
        public string BrandCode { get; set; }
        public Nullable<int> QTYOnHand { get; set; }
        public Nullable<int> StockOnHand { get; set; }
        public Nullable<int> QTYOnHandW { get; set; }
        public Nullable<int> StockOnHandW { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Description { get; set; }
        public string SKUCode { get; set; }
        public string Department { get; set; }
        public string DepartmentName { get; set; }
        public string Vendor { get; set; }
        public string MKCode { get; set; }
        public string ProductType { get; set; }
        public string StorageLocation { get; set; }
        public string StorageLocationDesc { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateBy { get; set; }
    }
}
