//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FSBT_HHT_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterSerialNumber
    {
        public int ID { get; set; }
        public string SKUCode { get; set; }
        public string Barcode { get; set; }
        public string SerialNumber { get; set; }
        public string StorageLocation { get; set; }
        public string StorageLocationDesc { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public string createby { get; set; }
    }
}
