//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FSBT_HHT_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MastSAP_SKU
    {
        public int ID { get; set; }
        public string PIDoc { get; set; }
        public string Year { get; set; }
        public string LineItem { get; set; }
        public string DateCreate { get; set; }
        public string CycleFullCount { get; set; }
        public string PIRefDoc { get; set; }
        public string Material { get; set; }
        public string MaterialDesc { get; set; }
        public string MaterialGroup { get; set; }
        public string MaterialGroupDesc { get; set; }
        public string SubDepartment { get; set; }
        public string SubDepartmentDesc { get; set; }
        public string WeightingValue { get; set; }
        public string Brand { get; set; }
        public string BrandDesc { get; set; }
        public string Plant { get; set; }
        public string PlantDesc { get; set; }
        public string StorageLocation { get; set; }
        public string StorageLocationDesc { get; set; }
        public string SpecialStock { get; set; }
        public string StockType { get; set; }
        public string Vendor { get; set; }
        public string WBS { get; set; }
        public string BaseUOM { get; set; }
        public string BookQTY { get; set; }
        public string CountedQTY { get; set; }
        public string ActualCountDate { get; set; }
        public string PlanCountDate { get; set; }
        public string SAPIDoc { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string FileName { get; set; }
        public string MCHLevel1 { get; set; }
        public string MCHLevel1Desc { get; set; }
        public string MCHLevel2 { get; set; }
        public string MCHLevel2Desc { get; set; }
        public string MCHLevel3 { get; set; }
        public string MCHLevel3Desc { get; set; }
        public string SerialNumber { get; set; }
    }
}
