//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FSBT_HHT_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Section
    {
        public string SectionCode { get; set; }
        public string SectionName { get; set; }
        public string StorageLocationCode { get; set; }
        public string PlantCode { get; set; }
        public string CountSheet { get; set; }
        public string MCHLevel1 { get; set; }
        public string MCHLevel2 { get; set; }
        public string MCHLevel3 { get; set; }
        public string MCHLevel4 { get; set; }
        public string LocationFrom { get; set; }
        public string LocationTo { get; set; }
        public string BrandCode { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public string UpdateBy { get; set; }
    }
}
