//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FSBT_HHT_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempFileBarcodeError
    {
        public int ID { get; set; }
        public string PIDoc { get; set; }
        public string Year { get; set; }
        public string Material { get; set; }
        public string AltUOM { get; set; }
        public string MarerialDesc { get; set; }
        public string BarCode { get; set; }
        public string EANCodeCat { get; set; }
        public string ConversionCounter { get; set; }
        public string ConversionDenominator { get; set; }
        public string BaseUOM { get; set; }
        public string SAPIdoc { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string TempFileName { get; set; }
        public string Error { get; set; }
        public int URNO { get; set; }
    }
}
