//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FSBT_HHT_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmp_MasterMapping
    {
        public int id { get; set; }
        public string Plant { get; set; }
        public string CountSheet { get; set; }
        public string StorageLocation { get; set; }
        public string SectionCode { get; set; }
        public string SKUCode { get; set; }
        public string Description { get; set; }
        public string InBarCode { get; set; }
        public string ExBarCode { get; set; }
        public string SerialNumber { get; set; }
        public string DepartmentCode { get; set; }
        public string MKCode { get; set; }
        public string ProductType { get; set; }
        public string Location { get; set; }
    }
}
