//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FSBT_HHT_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserReportConfig
    {
        public string ReportCode { get; set; }
        public string ConditionName { get; set; }
        public string ConditionObject { get; set; }
        public string DefaultValue { get; set; }
        public Nullable<bool> AllowChange { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdateBy { get; set; }
    
        public virtual UserReport UserReport { get; set; }
    }
}
